runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /.*
  script: lotto.app

# [START libraries]
libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

# [END libraries]
